kind: Pod
apiVersion: v1
metadata:
  name: env-test
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: k8s
        - name: author
          value: yaswanthbandela