kind: Pod
apiVersion: v1
metadata:
  name: nginx
  
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        valueFrom: 
          configMapKeyRef:
            name: daws78s
            key: course
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: daws78s
            key: trainer

